title: CV | Muhamad Rafli Maulana Rizki
description:  CV-Rafli.
url: https://cv.raflimaulanarizki.site
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-minifier

exclude:
  - docker-compose.yml